## Naive Bayes Classifier to classify species

In [1]:
# importing required packages
import pandas as pd
import numpy as np

In [2]:
# Reading the dataset
df = pd.read_csv('iris.csv')

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
X = df.drop('species',axis=1)
y= df['species']

In [5]:
# Splitting into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 48)

In [6]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [7]:
# Predicting the Test set results
y_pred = model.predict(X_test)
print(y_pred)

['versicolor' 'versicolor' 'versicolor' 'setosa' 'virginica' 'virginica'
 'setosa' 'virginica' 'setosa' 'versicolor' 'virginica' 'setosa' 'setosa'
 'virginica' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'virginica' 'setosa' 'virginica' 'virginica' 'versicolor' 'virginica'
 'setosa' 'setosa' 'virginica' 'virginica' 'versicolor' 'virginica'
 'versicolor' 'virginica' 'setosa' 'versicolor' 'virginica' 'virginica'
 'versicolor' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'virginica'
 'virginica' 'versicolor']


In [8]:
#lets see the actual and predicted value side by side
# The vstack() function is used to stack arrays in sequence vertically (row wise)
y_compare = np.vstack((y_test,y_pred)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 10 values
y_compare[:10,:]

array([['versicolor', 'versicolor'],
       ['versicolor', 'versicolor'],
       ['virginica', 'versicolor'],
       ['setosa', 'setosa'],
       ['versicolor', 'virginica'],
       ['virginica', 'virginica'],
       ['setosa', 'setosa'],
       ['virginica', 'virginica'],
       ['setosa', 'setosa'],
       ['versicolor', 'versicolor']], dtype=object)

In [9]:
from sklearn.metrics import accuracy_score
# Check for accuracy of the model
accuracy = accuracy_score(y_pred,y_test)* 100
accuracy

93.33333333333333

In [10]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11  0  0]
 [ 0 16  2]
 [ 0  1 15]]


In [11]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(cm.sum()))

Correct predictions:  42
False predictions 3


Accuracy of the Naive Bayes Clasification is:  0.9333333333333333
